language: c
dist: trusty
sudo: required

notifications:
  email: false
git:
  submodules: true
  depth: 3

matrix:
  include:

  - os: linux
    compiler: gcc
    install:
      - sudo apt-get install -y gcc-multilib
      - sudo apt-get install -y libc6-dev-i386
    script:
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_C_FLAGS=-m32
      - cmake --build . -std=c99 --config Release
      - cd ..

  - os: linux
    compiler: gcc
    script:
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_C_FLAGS=-m64
      - cmake --build .  -std=c99 --config Release
      - cd ..

  - os: osx
    compiler: gcc
    script:
      - mkdir build
      - cd build
      - cmake .. "-DCMAKE_OSX_ARCHITECTURES=i386;x86_64"
      - cmake --build . --config Release
      - cd ..
