//
// Created by Leonard Eyer on 09.07.20.
//

#ifndef DRUM_SHAPES_SOURCE_PROJECTS_PA_STRING_TILDE_STRINGMODEL_H_
#define DRUM_SHAPES_SOURCE_PROJECTS_PA_STRING_TILDE_STRINGMODEL_H_

float eigenFrequency(float stringLength, int index);

#endif //DRUM_SHAPES_SOURCE_PROJECTS_PA_STRING_TILDE_STRINGMODEL_H_
